#include "VertexFormats.cg"

float4 main(v2f IN,  uniform float4 ambientLightColor, uniform samplerCUBE colorMap : TEXUNIT0) : COLOR
{	
	//IN.TexCoords = mul(textureMatrix, IN.TexCoords);
	//float4 sample = tex2D(colorMap, IN.TexCoords.xz);
	float4 sample = texCUBE(colorMap, IN.Normal.xyz);
	sample *= IN.DiffuseLightColor + ambientLightColor;
	//sample *= IN.Material.y;
	return sample;
}